include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    public_member_api_docs: false
    require_trailing_commas: false

analyzer:
  plugins:
    - custom_lint
  errors:
    inference_failure_on_instance_creation: ignore