name: riverpod_firebase_pagination_example
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  ###  Firebase  ###
  firebase_core: any
  cloud_firestore: any
  ###  State Management  ###
  flutter_riverpod: any
  riverpod_annotation: any
  freezed_annotation: any
  json_serializable: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: any
  custom_lint: any
  riverpod_lint: any
  riverpod_generator: any
  build_runner: any
  freezed: any

flutter:
  uses-material-design: true
